class ValidatorException(Exception):
    pass

class RepoException(Exception):
    pass
